### PR TITLE
fix(statusbar): fix statusbar message

### PR DESCRIPTION
**Pull request by yi-Xu-0100**
The status bar should hide when the active editor language is different from `git-commit` whichever the document changed.

ref: #78

### CODE REVIEW

**Comment by yi-Xu-0100** [comment]
@joshbolduc I investigated which extension keeps triggering and outputting the language ID of `code-runner-output`, and finally found that it is `formulahendry.code-runner`. 😅

But after I close this extension, some others still trigger and outputs `Log`, This time I closed all the extensions and still couldn't solve it. 😢

So I checked the check logic here and felt that since there is a more precise judgment (judging whether the language ID of the currently active editor is `git-commit`), I can use it directly. Finally, if not, Then hide the `statusbar` directly, if it is, it should do grammatical judgment. 😀

**Comment by joshbolduc** [comment]
Do you have a set of repro steps for this bug? For me the status bar already seems to be hidden when I switch editors away from a `git-commit` type doc.

**Comment by yi-Xu-0100** [comment]
@joshbolduc Not a bug for the docs which is not the `git-commit` type. 😅

When the docs' language ID is `git-commit`, it still has triggered with a language ID of `Log` every second whether you change words or not(I have no other extension). This will lead the extension to use `updateStatusBar()`, But the language ID of the current active editor is `git-commit`, so it will not hide the `statusbar` but change the description with `0 rules loaded`.

My simple reproduction steps:

1. add a new txt as `test.txt`.
2. set the language ID of the `test.txt` to `git-commit`.
3. change the word to activate the extension.
4. It will show `0 rules loaded`.

image

**Comment by joshbolduc** [comment]
Oh, it looks like it's related to having the Output view open. Interesting....

**Comment by yi-Xu-0100** [comment]
@joshbolduc You are right. Only when I open the output channel view, will have a mistake with the `statusbar` message. 

It works well without the output channel opened. 😀

**Comment by joshbolduc** [comment]
Thanks for helping bring this issue to my attention! I ended up digging in a bit more and came up with a more minimal fix in #149. The status bar handling could use a rethink anyway, but for now I think it'll do.

**Pull request closed without merging**
