### PR TITLE
fix: support absolute path

### PR DESCRIPTION
**Pull request by yi-Xu-0100**
closes: #81

### CODE REVIEW

**Comment by joshbolduc** [comment]
I'm surprised this fixes the problem. It looks like [`@commitlint/load` already uses `path.resolve`](https://github.com/conventional-changelog/commitlint/blob/81c38ddf15f239b525f673b26b2ee6606f2ee8f6/%40commitlint/load/src/utils/load-config.ts#L16) so this _looks_ like it should be a no-op, and when I test absolute paths seem to work fine with *nix-based paths. (I don't have a Windows dev env handy right now to test, but still can't tell why `load` wouldn't handle it anyway.)

Not sure what I'm missing....

**Comment by yi-Xu-0100** [comment]
@joshbolduc I think so simply, so I did not test. 😅 

And this time I test it in windows. It works well! 😀

**Comment by yi-Xu-0100** [comment]
@joshbolduc I rebase the code with the main branch and test in my windows. It works well with the absolute path. Should this merge into the main branch? 😀

**Review by joshbolduc — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
